// ── Supported Devices Data ────────────────────────────────────────────────
//
// Source of truth for statuses is the driver registry in `@openmouse/protocol`
// (`src/drivers/registry.ts`). Keep the statuses below in sync with it:
//
//   supported  — a driver in `@openmouse/protocol` covers the device (and, for
//                the ones with a `pids` field, those PIDs exist in the
//                protocol registry). Verified hardware reports are preferred.
//   pr         — a pull request that adds the driver is open.
//   quickwin   — the protocol is implemented; only a PID/config entry is
//                missing (a small addition to the existing driver).
//   likely     — a driver exists that probably covers the model, but the exact
//                PID/interface has not been confirmed on hardware.
//   driver     — no driver exists; the protocol is not implemented.
//   unknown    — nothing is known about the protocol.
//   bridge     — a driver exists but the device's settings channel is out of
//                WebHID reach; configuration requires the OpenMouse Bridge
//                desktop companion (native control).
//   pending    — a community request nobody has looked into yet. Imported
//                from the retired Supabase request catalog; they sit at the
//                bottom of the table.
//
// `src/supported-mice.test.ts` re-checks every `supported`/`quickwin` claim and
// every PID against the protocol package so this table cannot silently drift
// from the code again. `src/supported-registry.ts` additionally adds the
// registry-listed supported models.

export type Status = "supported" | "pr" | "quickwin" | "likely" | "driver" | "unknown" | "bridge" | "pending";

export interface Mouse {
  brand: string;
  model: string;
  status: Status;
  /** Request votes, frozen from the retired Supabase request catalog. */
  req: number;
  note: string;
  /** Known product IDs, where the protocol pins them (checked by tests). */
  pids?: readonly number[];
}

export const STATUS: Record<Status, { label: string; order: number }> = {
  supported: { label: "Supported",     order: 0 },
  pr:        { label: "PR pending",    order: 1 },
  quickwin:  { label: "Quick Win",     order: 2 },
  likely:    { label: "Test Needed",   order: 3 },
  driver:    { label: "Driver Needed", order: 4 },
  unknown:   { label: "Unknown",       order: 5 },
  bridge:    { label: "Needs Bridge",  order: 6 },
  pending:   { label: "Requested",     order: 7 },
};

export const TABS: Array<{ key: Status | "all"; label: string }> = [
  { key: "all",       label: "All" },
  { key: "supported", label: "Supported" },
  { key: "pr",        label: "PR pending" },
  { key: "quickwin",  label: "Quick Win" },
  { key: "likely",    label: "Test Needed" },
  { key: "driver",    label: "Driver Needed" },
  { key: "unknown",   label: "Unknown" },
  { key: "bridge",    label: "Needs Bridge" },
  { key: "pending",   label: "Requested" },
];

export const MICE: Mouse[] = [
  // LOGITECH ─────────────────────────────────────────────────────────────
  { brand: "Logitech", model: "G502 (all variants)",    status: "supported", req: 77,
    pids: [0xc07d, 0xc08b],
    note: "Wired PIDs 0xc07d (G502) / 0xc08b (HERO) in driver; Lightspeed dongle variants also work" },
  { brand: "Logitech", model: "G203 LIGHTSYNC",         status: "supported", req: 9,
    pids: [0xc092],
    note: "PID 0xc092 — HID++ direct, legacy DPI feature 0x2201" },
  { brand: "Logitech", model: "G203 PRODIGY",           status: "supported", req: 2,
    pids: [0xc084],
    note: "PID 0xc084 — HID++ direct, legacy DPI feature 0x2201" },
  { brand: "Logitech", model: "G102 LIGHTSYNC",         status: "supported", req: 7,
    pids: [0xc089],
    note: "PID 0xc089 — same family as G203, HID++ direct" },
  { brand: "Logitech", model: "G402 Hyperion Fury",     status: "supported", req: 13,
    pids: [0xc07e],
    note: "PID 0xc07e — HID++ direct, legacy DPI feature 0x2201" },
  { brand: "Logitech", model: "G303 Daedalus Apex",     status: "supported", req: 1,
    pids: [0xc080],
    note: "PID 0xc080 — HID++ direct" },
  { brand: "Logitech", model: "G303 Shroud Edition",    status: "supported", req: 1,
    note: "Lightspeed dongle — HID++ 2.0 protocol supported" },
  { brand: "Logitech", model: "G Pro (2017)",           status: "supported", req: 2,
    pids: [0xc085],
    note: "PID 0xc085 — HID++ direct, DPI feature 0x2202" },
  { brand: "Logitech", model: "G502 HERO (wired)",      status: "supported", req: 4,
    pids: [0xc08b],
    note: "PID 0xc08b — HID++ direct, DPI feature 0x2202" },
  { brand: "Logitech", model: "G Pro Hero",             status: "supported", req: 2,
    pids: [0xc08c],
    note: "PID 0xc08c — HID++ direct" },
  { brand: "Logitech", model: "G903 HERO (wired)",      status: "supported", req: 2,
    pids: [0xc08e],
    note: "PID 0xc08e — HID++ direct" },
  { brand: "Logitech", model: "G903 Lightspeed",        status: "supported", req: 5,
    note: "Lightspeed dongle — HID++ 2.0 protocol supported" },
  { brand: "Logitech", model: "G403 HERO (wired)",      status: "supported", req: 1,
    pids: [0xc08f],
    note: "PID 0xc08f — HID++ direct, DPI feature 0x2202" },
  { brand: "Logitech", model: "G703 (wired)",           status: "supported", req: 1,
    note: "PID 0xc087 — HID++ direct, legacy DPI 0x2201, onboard format 3 (HEAT) writable" },
  { brand: "Logitech", model: "G703 Lightspeed",        status: "supported", req: 0,
    note: "Lightspeed dongle — HID++ 2.0 protocol supported" },
  { brand: "Logitech", model: "G Pro X Superlight",     status: "supported", req: 18,
    pids: [0xc094],
    note: "PID 0xc094 — HID++ direct" },
  { brand: "Logitech", model: "PRO X SUPERLIGHT 2",     status: "supported", req: 0,
    pids: [0xc09b],
    note: "PID 0xc09b — HID++ direct" },
  { brand: "Logitech", model: "PRO X SUPERLIGHT 2 SE",  status: "supported", req: 0,
    note: "Shares the PRO X SUPERLIGHT 2 PID 0xc09b — HID++ direct; no separate USB id" },
  { brand: "Logitech", model: "PRO X SUPERLIGHT 2 DEX", status: "supported", req: 2,
    pids: [0xc0a0],
    note: "PID 0xc0a0 — HID++ direct" },
  { brand: "Logitech", model: "PRO X2 SUPERSTRIKE",     status: "supported", req: 8,
    pids: [0xc0a8, 0x40bd],
    note: "Lightspeed receivers 0xc0a8 (USB) / 0x40bd (dedicated) — HID++ 2.0 protocol supported" },
  { brand: "Logitech", model: "PRO X3 SUPERSTRIKE",     status: "supported", req: 0,
    pids: [0xc54f],
    note: "Lightspeed receiver 0xc54f — HID++ 2.0 protocol supported; verified on hardware (DPI stage list not decoded yet)" },
  { brand: "Logitech", model: "G305",                   status: "supported", req: 27,
    note: "Lightspeed receiver — HID++ 2.0 protocol supported" },
  { brand: "Logitech", model: "MX Master 3S",           status: "supported", req: 32,
    pids: [0xc548],
    note: "Logi Bolt receiver (0xc548) already in driver" },
  { brand: "Logitech", model: "G502 X (wired)",         status: "supported", req: 39,
    pids: [0xc099],
    note: "PID 0xc099 — HID++ direct, in driver" },
  { brand: "Logitech", model: "G502 X PLUS (wireless)", status: "supported", req: 31,
    pids: [0xc095],
    note: "PID 0xc095 (USB) in driver; Lightspeed dongle also works" },
  { brand: "Logitech", model: "G502 X LIGHTSPEED",      status: "supported", req: 9,
    pids: [0xc098],
    note: "Lightspeed dongle — HID++ 2.0 protocol supported; PID 0xc098 (USB cable, direct-connect) also in driver" },
  { brand: "Logitech", model: "MX Vertical",            status: "driver",    req: 12,
    note: "Unifying (HID++ 1.0) / Bluetooth — not implemented" },
  { brand: "Logitech", model: "MX Master 4",            status: "supported", req: 17,
    note: "Bluetooth (HID++ on vendor page 0xFF43) and Logi Bolt receiver both in driver" },
  { brand: "Logitech", model: "MX Master 4S",           status: "likely",    req: 8,
    note: "Logi Bolt receiver in driver — needs hardware test" },
  { brand: "Logitech", model: "G304",                   status: "supported", req: 12,
    note: "Lightspeed receiver — HID++ 2.0 protocol supported" },
  { brand: "Logitech", model: "G Pro Wireless",         status: "supported", req: 14,
    note: "Lightspeed dongle — HID++ 2.0 protocol supported" },
  { brand: "Logitech", model: "G300s",                  status: "driver",    req: 6,
    note: "Older HID++ 1.0 protocol variant — not implemented" },
  { brand: "Logitech", model: "G600",                   status: "driver",    req: 8,
    note: "HID++ 1.0 protocol variant — not yet implemented" },
  { brand: "Logitech", model: "G604 LIGHTSPEED",        status: "supported", req: 2,
    note: "Lightspeed dongle — HID++ 2.0 protocol supported" },
  { brand: "Logitech", model: "G Pro 2 Lightspeed",     status: "supported", req: 4,
    pids: [0xc09a],
    note: "USB PID 0xc09a (direct-connect) in driver; Lightspeed dongle also works" },
  { brand: "Logitech", model: "G502 Lightspeed",        status: "supported", req: 2,
    note: "Lightspeed USB dongle — HID++ 2.0 protocol supported" },
  { brand: "Logitech", model: "MX Master 2S",           status: "driver",    req: 2,
    note: "Unifying receiver (HID++ 1.0) — not implemented" },
  { brand: "Logitech", model: "MX Anywhere 3",          status: "supported", req: 2,
    pids: [0xc548],
    note: "Logi Bolt receiver (0xc548) in driver" },
  { brand: "Logitech", model: "MX Anywhere 3S",         status: "supported", req: 0,
    pids: [0xc548],
    note: "Logi Bolt receiver (0xc548) in driver" },
  { brand: "Logitech", model: "G309 Lightspeed",        status: "supported", req: 1,
    note: "Lightspeed USB dongle — HID++ 2.0 protocol supported" },
  { brand: "Logitech", model: "MX Ergo S",              status: "supported", req: 4,
    pids: [0xc548],
    note: "Logi Bolt receiver (0xc548) in driver" },
  { brand: "Logitech", model: "MX Anywhere 2",          status: "driver",    req: 1,
    note: "Unifying receiver (HID++ 1.0) — not implemented" },
  { brand: "Logitech", model: "Compact Wireless",       status: "unknown",   req: 1,
    note: "Protocol unknown — receiver type needs identification" },
  { brand: "Logitech", model: "G700s",                  status: "driver",    req: 2,
    note: "HID++ 1.0 (legacy protocol) — not implemented" },
  { brand: "Logitech", model: "M171 Wireless",          status: "driver",    req: 1,
    note: "Basic optical — no HID++ control channel exposed" },

  // ROCCAT ─────────────────────────────────────────────────────────────
  { brand: "Roccat", model: "Kone Pro Air",             status: "driver",    req: 89,
    note: "Roccat Swarm / AIMO protocol — not implemented" },
  { brand: "Roccat", model: "Kone XP Air",              status: "driver",    req: 8,
    note: "Roccat AIMO protocol — not implemented" },
  { brand: "Roccat", model: "Tyon",                     status: "driver",    req: 3,
    note: "Roccat protocol — not implemented" },
  { brand: "Roccat", model: "Nyth",                     status: "driver",    req: 2,
    note: "Roccat protocol — not implemented" },
  { brand: "Roccat", model: "Kain 100 AIMO",            status: "driver",    req: 2,
    note: "Roccat AIMO protocol — not implemented" },
  { brand: "Roccat", model: "Kone Pro",                 status: "driver",    req: 1,
    note: "Roccat protocol — not implemented" },

  // REDRAGON ─────────────────────────────────────────────────────────────
  { brand: "Redragon", model: "M725 Honeycomb",         status: "driver",    req: 37,
    note: "Redragon HID protocol — not implemented" },
  { brand: "Redragon", model: "Impact Elite M913",      status: "driver",    req: 24,
    note: "Redragon HID protocol — not implemented" },
  { brand: "Redragon", model: "PREDATOR M612",          status: "driver",    req: 3,
    note: "Redragon HID protocol — not implemented" },
  { brand: "Redragon", model: "K1ng M916 Pro 4K",      status: "driver",    req: 6,
    note: "Redragon HID protocol — not implemented" },
  { brand: "Redragon", model: "M711 Cobra",             status: "driver",    req: 3,
    note: "Redragon HID protocol — not implemented" },
  { brand: "Redragon", model: "M917 Pro",               status: "driver",    req: 3,
    note: "Redragon HID protocol — not implemented" },
  { brand: "Redragon", model: "M991",                   status: "driver",    req: 2,
    note: "Redragon HID protocol — not implemented" },
  { brand: "Redragon", model: "M703",                   status: "driver",    req: 2,
    note: "Redragon HID protocol — not implemented" },
  { brand: "Redragon", model: "TAIPAN PRO M810",        status: "driver",    req: 6,
    note: "Redragon HID protocol — not implemented" },
  { brand: "Redragon", model: "Ranger Lite",            status: "driver",    req: 1,
    note: "Redragon HID protocol — not implemented" },
  { brand: "Redragon", model: "Infernal Dragon",        status: "driver",    req: 1,
    note: "Redragon HID protocol — not implemented" },
  { brand: "Redragon", model: "M696 Pro",               status: "driver",    req: 1,
    note: "Redragon HID protocol — not implemented" },
  { brand: "Redragon", model: "M721 Pro",               status: "driver",    req: 1,
    note: "Redragon HID protocol — not implemented" },
  // The protocol's Redragon driver currently claims exactly one product; the
  // rest of the lineup still needs work.
  { brand: "Redragon", model: "M724 K1NG 1K",           status: "supported", req: 4,
    pids: [0xfc7a],
    note: "PID 0xfc7a in Redragon driver — DPI table writes (5 stages, up to 12400) verified on hardware" },

  // RYUNIX ──────────────────────────────────────────────────────────────
  { brand: "Ryunix",   model: "KYU Pro MX1",            status: "supported", req: 0,
    pids: [0x026e, 0x026f],
    note: "PIDs 0x026e (wired) / 0x026f (wireless) in the Ryunix driver (VID 0x04f3)" },

  // DELUX ───────────────────────────────────────────────────────────────
  { brand: "Delux",    model: "M800 Mini",              status: "supported", req: 0,
    pids: [0xfa60, 0xfa55],
    note: "PIDs 0xfa60 (wireless) / 0xfa55 (wired) in the Delux driver (X11-style firmware on OEM VID 0x1d57)" },

  // DAREU ───────────────────────────────────────────────────────────────
  { brand: "Dareu",    model: "A950 PRO Mg",            status: "supported", req: 1,
    pids: [0x1114, 0x1117],
    note: "TM265 receiver 0x1114 verified on hardware; the wired direct link 0x1117 is accepted by the driver but untested (VID 0x260d)" },

  // ATTACK SHARK ────────────────────────────────────────────────────────
  { brand: "Attack Shark", model: "X3",                 status: "bridge",    req: 56,
    note: "Not compatible with WebHID — needs the OpenMouse Bridge companion (0x25a7 GearHub protocol)" },
  { brand: "Attack Shark", model: "X11",                status: "bridge",    req: 53,
    note: "Not compatible with WebHID — needs the OpenMouse Bridge companion (0x1d57 / 0x25a7 families)" },
  { brand: "Attack Shark", model: "R5 Ultra",           status: "supported", req: 11,
    pids: [0x0046, 0x0047],
    note: "PIDs 0x0046/0x0047 in the CompX/Lamzu driver (R5 Ultra profile)" },
  { brand: "Attack Shark", model: "X6",                 status: "bridge",    req: 23,
    note: "Not compatible with WebHID — needs the OpenMouse Bridge companion (0x25a7 GearHub protocol)" },
  { brand: "Attack Shark", model: "R3",                 status: "likely",    req: 6,
    pids: [0x402d, 0x4026],
    note: "GearHub R3 profile (device id 1643 = PAW3395, 3309 = PAW3950) shares the 0x402d dongle / 0x4026 cable — not hardware-verified yet" },
  { brand: "Attack Shark", model: "R1",                 status: "bridge",    req: 7,
    note: "Not compatible with WebHID — needs the OpenMouse Bridge companion (0x1d57 family)" },
  { brand: "Attack Shark", model: "X8 Ultra",           status: "bridge",    req: 3,
    note: "Not compatible with WebHID — needs the OpenMouse Bridge companion (0x25a7 GearHub protocol)" },
  { brand: "Attack Shark", model: "X8 SE",              status: "bridge",    req: 12,
    note: "Not compatible with WebHID — needs the OpenMouse Bridge companion (0x1d57 VID, GearHub protocol)" },
  { brand: "Attack Shark", model: "X1",                 status: "bridge",    req: 3,
    note: "Not compatible with WebHID — needs the OpenMouse Bridge companion (0x25a7 GearHub protocol)" },
  { brand: "Attack Shark", model: "V3 Pro",             status: "bridge",    req: 11,
    note: "Not compatible with WebHID — needs the OpenMouse Bridge companion (0x25a7 GearHub protocol)" },
  { brand: "Attack Shark", model: "X3 Pro",             status: "bridge",    req: 4,
    note: "Not compatible with WebHID — needs the OpenMouse Bridge companion (0x25a7 GearHub protocol)" },
  { brand: "Attack Shark", model: "X11 SE",             status: "bridge",    req: 4,
    note: "Not compatible with WebHID — needs the OpenMouse Bridge companion (0x1d57 / 0x25a7 families)" },
  { brand: "Attack Shark", model: "X8 PLUS",            status: "bridge",    req: 2,
    note: "Not compatible with WebHID — needs the OpenMouse Bridge companion (0x25a7 GearHub protocol)" },
  { brand: "Attack Shark", model: "X12",                status: "bridge",    req: 1,
    note: "Not compatible with WebHID — needs the OpenMouse Bridge companion (0x25a7 family)" },
  { brand: "Attack Shark", model: "R6",                 status: "bridge",    req: 5,
    note: "Not compatible with WebHID — needs the OpenMouse Bridge companion (0x25a7 family)" },
  { brand: "Attack Shark", model: "G3",                 status: "bridge",    req: 3,
    note: "Not compatible with WebHID — needs the OpenMouse Bridge companion (0x25a7 family)" },
  { brand: "Attack Shark", model: "R2",                 status: "supported", req: 2,
    pids: [0x402d, 0x4026],
    note: "Shares VID:PID 0x3151:0x402D with the Lingbao M5 Pro; GearHub driver identifies it by device id 1893/3009 — verified on hardware over 2.4 GHz and by cable (0x4026)" },

  // LINGBAO / GEARHUB ───────────────────────────────────────────────────
  { brand: "Lingbao", model: "M5 Pro",                  status: "supported", req: 0,
    pids: [0x402d, 0x4026],
    note: "Shares VID:PID with the Attack Shark R2 — GearHub driver identifies it by device id 2285; verified on hardware over 2.4 GHz and by cable (0x4026)" },

  // RAZER ───────────────────────────────────────────────────────────────
  { brand: "Razer", model: "DeathAdder V3 (wired)",     status: "supported", req: 20,
    note: "Confirmed working ✓" },
  { brand: "Razer", model: "DeathAdder V2 (wired)",     status: "supported", req: 14,
    pids: [0x0084],
    note: "PID 0x0084 — specific driver filter" },
  { brand: "Razer", model: "DeathAdder V2 Pro",         status: "supported", req: 8,
    pids: [0x007c, 0x007d],
    note: "PIDs 0x007c/0x007d in Razer registry" },
  { brand: "Razer", model: "Cobra",                     status: "supported", req: 4,
    pids: [0x00a3],
    note: "PID 0x00a3 — specific driver filter" },
  { brand: "Razer", model: "Viper V3 Pro",              status: "supported", req: 12,
    pids: [0x00c0, 0x00c1],
    note: "PIDs 0x00c0 / 0x00c1 — specific driver filter" },
  { brand: "Razer", model: "Viper V2 Pro",              status: "supported", req: 1,
    pids: [0x00a5, 0x00a6],
    note: "PIDs 0x00a5 (wired) / 0x00a6 (wireless) — verified on hardware, 1000 Hz stock receiver" },
  { brand: "Razer", model: "Viper V2 Pro (HyperPolling 8000 Hz)", status: "likely", req: 1,
    pids: [0x00b3],
    note: "PID 0x00b3 — standalone HyperPolling Wireless Dongle, driven generically off the DeathAdder V3 Pro's Focus Pro ceiling; forwards settings to whatever mouse is paired, not yet verified against a Viper V2 Pro specifically" },
  { brand: "Razer", model: "DeathAdder Essential",      status: "supported", req: 1,
    pids: [0x006e, 0x0071, 0x0098],
    note: "PIDs 0x006e / 0x0071 / 0x0098 — specific driver filters" },
  { brand: "Razer", model: "Viper Mini",                status: "supported", req: 9,
    pids: [0x008a],
    note: "PID 0x008a — dedicated Viper Mini driver" },
  { brand: "Razer", model: "Viper V3 HyperSpeed",       status: "supported", req: 8,
    pids: [0x00b8],
    note: "PID 0x00b8 — verified on hardware" },
  { brand: "Razer", model: "Viper V4 Pro",              status: "supported", req: 3,
    pids: [0x00e5, 0x00e6],
    note: "PIDs 0x00e5 (wired) / 0x00e6 (wireless) — dedicated driver, only mouse on Razer's own Synapse Web" },
  { brand: "Razer", model: "Basilisk V3 (wired)",       status: "likely",    req: 78,
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "Basilisk V3 Pro",           status: "likely",    req: 42,
    note: "Wireless — in Razer registry, needs HyperSpeed dongle" },
  { brand: "Razer", model: "Viper Ultimate",            status: "likely",    req: 18,
    note: "Wired 0x007a works; wireless 0x007b is nativeOnly (Chrome won't expose control)" },
  { brand: "Razer", model: "Basilisk V3 X HyperSpeed",  status: "likely",    req: 13,
    pids: [0x00b9],
    note: "Wireless — PID 0x00b9 in Razer registry" },
  { brand: "Razer", model: "DeathAdder V2 X HyperSpeed",status: "likely",    req: 7,
    note: "Wireless — in Razer registry" },
  { brand: "Razer", model: "Viper 8KHz",                status: "likely",    req: 1,
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "Naga V2 Pro",               status: "likely",    req: 10,
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "DeathAdder V3 Pro",         status: "supported", req: 7,
    pids: [0x00b6, 0x00b7],
    note: "PIDs 0x00b6 (wired) / 0x00b7 (HyperSpeed receiver) — both verified on hardware, firmware 2.1" },
  { brand: "Razer", model: "DeathAdder V4 Pro",         status: "supported", req: 12,
    pids: [0x00be, 0x00bf],
    note: "PIDs 0x00be (wired) / 0x00bf (wireless) — was nativeOnly until Razer's own live device list started reaching it over WebHID again" },
  { brand: "Razer", model: "DeathAdder V4 Pro Carbon Fiber Edition", status: "supported", req: 1,
    pids: [0x00ef, 0x00f0],
    note: "PIDs 0x00ef (wired) / 0x00f0 (wireless) — same driver as the standard edition, cosmetic SKU" },
  { brand: "Razer", model: "Naga Trinity",              status: "likely",    req: 70,
    note: "PID 0x0067 in Razer registry — standard transport" },
  { brand: "Razer", model: "Naga X",                    status: "likely",    req: 3,
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "Basilisk Essential",        status: "likely",    req: 1,
    note: "In Razer device registry" },
  { brand: "Razer", model: "Basilisk",                  status: "likely",    req: 1,
    note: "In Razer device registry" },
  { brand: "Razer", model: "Orochi V2",                 status: "likely",    req: 3,
    note: "Wireless — in Razer registry" },
  { brand: "Razer", model: "Cobra Pro",                  status: "likely",    req: 2,
    pids: [0x00af, 0x00b0],
    note: "Razer registry name for the wireless Cobra — PIDs 0x00af (wired) / 0x00b0 (wireless), needs hardware test" },
  { brand: "Razer", model: "Viper V3 Pro SE",           status: "likely",    req: 5,
    pids: [0x00de, 0x00df],
    note: "PIDs 0x00de/0x00df now in Razer registry — needs hardware test" },
  { brand: "Razer", model: "Basilisk X HyperSpeed",     status: "likely",    req: 12,
    note: "Wireless — in Razer registry" },
  { brand: "Razer", model: "Naga V2 HyperSpeed",        status: "likely",    req: 12,
    note: "Wireless — in Razer registry" },
  { brand: "Razer", model: "Basilisk Ultimate",         status: "likely",    req: 3,
    note: "Wireless — in Razer registry" },
  { brand: "Razer", model: "DeathAdder Elite",          status: "likely",    req: 3,
    pids: [0x005c],
    note: "PID 0x005c in Razer registry — standard transport" },
  // Remaining models in the Razer product registry (drivers/razer/devices.ts).
  // They all speak the standard Razer HID protocol but none has been exercised
  // on hardware yet, so they stay "test needed".
  { brand: "Razer", model: "Abyssus 1800",              status: "likely",    req: 0,
    pids: [0x0020],
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "Abyssus 2000",              status: "likely",    req: 0,
    pids: [0x005e],
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "Abyssus 2014",              status: "likely",    req: 0,
    pids: [0x0042],
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "Abyssus Elite (D.Va Edition)", status: "likely", req: 0,
    pids: [0x006a],
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "Abyssus Essential",         status: "likely",    req: 0,
    pids: [0x006b],
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "Abyssus V2",                status: "likely",    req: 0,
    pids: [0x005b],
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "Atheris",                   status: "likely",    req: 3,
    pids: [0x0062],
    note: "Wireless — in Razer registry" },
  { brand: "Razer", model: "Basilisk Mobile",           status: "likely",    req: 0,
    pids: [0x00d3, 0x00d4],
    note: "PIDs 0x00d3 (wired) / 0x00d4 (wireless) in Razer registry" },
  { brand: "Razer", model: "Basilisk V2",               status: "likely",    req: 1,
    pids: [0x0085],
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "Basilisk V3 35K",           status: "likely",    req: 0,
    pids: [0x00cb],
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "Basilisk V3 Pro 35K",       status: "likely",    req: 0,
    pids: [0x00cc, 0x00cd],
    note: "PIDs 0x00cc (wired) / 0x00cd (wireless) in Razer registry" },
  { brand: "Razer", model: "Basilisk V3 Pro 35K Phantom Green", status: "likely", req: 0,
    pids: [0x00d6, 0x00d7],
    note: "PIDs 0x00d6 (wired) / 0x00d7 (wireless) in Razer registry — cosmetic SKU" },
  { brand: "Razer", model: "DeathAdder 1800",           status: "likely",    req: 0,
    pids: [0x0038],
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "DeathAdder 2000",           status: "likely",    req: 0,
    pids: [0x004f],
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "DeathAdder 2013",           status: "likely",    req: 0,
    pids: [0x0037],
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "DeathAdder 3500",           status: "likely",    req: 0,
    pids: [0x0054],
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "DeathAdder Chroma",         status: "likely",    req: 0,
    pids: [0x0043],
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "DeathAdder V2 Lite",        status: "likely",    req: 0,
    pids: [0x00a1],
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "DeathAdder V2 Mini",        status: "likely",    req: 0,
    pids: [0x008c],
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "DeathAdder V3 HyperSpeed",  status: "likely",    req: 4,
    pids: [0x00c4, 0x00c5],
    note: "PIDs 0x00c4 (wired) / 0x00c5 (wireless) in Razer registry" },
  { brand: "Razer", model: "Diamondback Chroma",        status: "likely",    req: 0,
    pids: [0x004c],
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "Imperator 2012",            status: "likely",    req: 0,
    pids: [0x002f],
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "Lancehead",                 status: "likely",    req: 0,
    pids: [0x0059, 0x005a],
    note: "PIDs 0x0059 (wired) / 0x005a (wireless) in Razer registry" },
  { brand: "Razer", model: "Lancehead Tournament Edition", status: "likely", req: 2,
    pids: [0x0060],
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "Lancehead Wireless",        status: "likely",    req: 0,
    pids: [0x006f, 0x0070],
    note: "PIDs 0x006f (wired) / 0x0070 (wireless) in Razer registry" },
  { brand: "Razer", model: "Mamba",                     status: "likely",    req: 0,
    pids: [0x0044, 0x0045],
    note: "PIDs 0x0044 (wired) / 0x0045 (wireless) in Razer registry" },
  { brand: "Razer", model: "Mamba 2012",                status: "likely",    req: 0,
    pids: [0x0024, 0x0025],
    note: "PIDs 0x0024 (wired) / 0x0025 (wireless) in Razer registry" },
  { brand: "Razer", model: "Mamba Elite",               status: "likely",    req: 1,
    pids: [0x006c],
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "Mamba Tournament Edition",  status: "likely",    req: 2,
    pids: [0x0046],
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "Mamba Wireless",            status: "likely",    req: 0,
    pids: [0x0072, 0x0073],
    note: "PIDs 0x0072 (wired) / 0x0073 (wireless) in Razer registry" },
  { brand: "Razer", model: "Naga",                      status: "likely",    req: 0,
    pids: [0x0015],
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "Naga 2012",                 status: "likely",    req: 0,
    pids: [0x002e],
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "Naga 2014",                 status: "likely",    req: 0,
    pids: [0x0040],
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "Naga Chroma",               status: "likely",    req: 0,
    pids: [0x0053],
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "Naga Epic",                 status: "likely",    req: 0,
    pids: [0x001f],
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "Naga Epic Chroma",          status: "likely",    req: 0,
    pids: [0x003e, 0x003f],
    note: "PIDs 0x003e (wired) / 0x003f (wireless) in Razer registry" },
  { brand: "Razer", model: "Naga Hex",                  status: "likely",    req: 0,
    pids: [0x0041],
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "Naga Hex (Red)",            status: "likely",    req: 0,
    pids: [0x0036],
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "Naga Hex V2",               status: "likely",    req: 0,
    pids: [0x0050],
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "Naga Left-Handed Edition 2020", status: "likely", req: 0,
    pids: [0x008d],
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "Naga Pro",                  status: "likely",    req: 4,
    pids: [0x008f, 0x0090],
    note: "PIDs 0x008f (wired) / 0x0090 (wireless) in Razer registry" },
  { brand: "Razer", model: "Orochi",                    status: "likely",    req: 0,
    pids: [0x0048],
    note: "Wired PID 0x0048 in Razer registry" },
  { brand: "Razer", model: "Orochi 2013",               status: "likely",    req: 0,
    pids: [0x0039],
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "Ouroboros 2012",            status: "likely",    req: 0,
    pids: [0x0032],
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "Pro Click",                 status: "likely",    req: 0,
    pids: [0x0077, 0x0080],
    note: "PIDs 0x0077 (wireless) / 0x0080 (wired) in Razer registry" },
  { brand: "Razer", model: "Pro Click Mini",            status: "likely",    req: 0,
    pids: [0x009a],
    note: "Wireless — in Razer registry" },
  { brand: "Razer", model: "Pro Click V2",              status: "likely",    req: 0,
    pids: [0x00d0, 0x00d1],
    note: "PIDs 0x00d0 (wired) / 0x00d1 (wireless) in Razer registry" },
  { brand: "Razer", model: "Pro Click V2 Vertical Edition", status: "likely", req: 0,
    pids: [0x00c7, 0x00c8],
    note: "PIDs 0x00c7 (wired) / 0x00c8 (wireless) in Razer registry" },
  { brand: "Razer", model: "Taipan",                    status: "likely",    req: 0,
    pids: [0x0034],
    note: "In Razer registry — needs hardware test" },
  { brand: "Razer", model: "Viper Mini Signature Edition", status: "likely", req: 2,
    pids: [0x009e, 0x009f],
    note: "PIDs 0x009e (wired) / 0x009f (wireless) in Razer registry — needs hardware test" },

  // HYPERX ─────────────────────────────────────────────────────────────
  { brand: "HyperX", model: "Pulsefire Haste",            status: "likely",      req: 19,
    pids: [0x1727, 0x0f8f, 0x048e, 0x028e],
    note: "Read/write: DPI (per-profile, onboard save), polling rate, and 2-step lift-off distance; hardware info, connection type, and battery (wireless) are read live. PIDs 0x1727 (Kingston-era wired), 0x0f8f/0x048e (HP-era wired / wired-mode), 0x028e (wireless dongle) in the HyperX driver" },
  { brand: "HyperX", model: "Pulsefire Haste 2",          status: "driver",  req: 19,
    note: "Kingston NGENUITY protocol — not implemented" },
  { brand: "HyperX", model: "Pulsefire Haste 2 Wireless", status: "driver",  req: 8,
    note: "Kingston NGENUITY protocol — not implemented" },
  { brand: "HyperX", model: "Pulsefire FPS Pro",          status: "driver",  req: 2,
    note: "Kingston NGENUITY protocol — not implemented" },
  { brand: "HyperX", model: "Pulsefire Fuse",             status: "driver",  req: 1,
    note: "Kingston NGENUITY protocol — not implemented" },

  // STEELSERIES ─────────────────────────────────────────────────────────
  { brand: "SteelSeries", model: "Aerox 9 Wireless",    status: "supported", req: 9,
    pids: [0x185a, 0x1876, 0x1858, 0x1874],
    note: "Write-only settings (DPI presets, polling, RGB zones/reactive/sleep-dim timers/rainbow/default lighting; no button-remap command in rivalcfg's profile for this device); battery percentage/charging is read live (no firmware-query command). PID 0x185a/0x1876 (wired mode) and 0x1858/0x1874 (2.4 GHz mode, WOW Edition) in SteelSeries Aerox 9 Wireless driver" },
  { brand: "SteelSeries", model: "Sensei Ten",           status: "supported", req: 13,
    pids: [0x1832, 0x1834],
    note: "Write-only: DPI presets (linear TrueMove3+-family encoding, not a lookup table), polling, logo/wheel LED RGB gradients, buttons; firmware version is read live. PID 0x1832 and 0x1834 (CS:GO Neon Rider Edition) in SteelSeries Sensei TEN driver" },
  { brand: "SteelSeries", model: "Aerox 5",              status: "supported", req: 5,
    pids: [0x1850, 0x1854, 0x185e, 0x1862, 0x1852, 0x185c, 0x1860],
    note: "Write-only settings (DPI presets, polling, RGB zones/reactive/brightness/rainbow, buttons); the Wireless variant's battery percentage/charging is read live. PID 0x1850 in SteelSeries Aerox 5 driver, 0x1854/0x185e/0x1862 (wired mode) and 0x1852/0x185c/0x1860 (2.4 GHz mode) in SteelSeries Aerox 5 Wireless driver" },
  { brand: "SteelSeries", model: "Rival 3 Wireless",     status: "supported", req: 2,
    pids: [0x1830],
    note: "DPI presets, polling, and buttons are write-only; battery percentage/charging and firmware are read live. PID 0x1830 (2.4 GHz mode) in SteelSeries Rival 3 Wireless driver" },
  { brand: "SteelSeries", model: "Rival 3 (wired)",      status: "supported", req: 15,
    pids: [0x1824, 0x184c],
    note: "DPI presets, polling, and buttons are write-only; firmware is read live. PIDs 0x1824/0x184c in SteelSeries Rival 3 driver" },
  { brand: "SteelSeries", model: "Rival 650 Wireless",   status: "supported", req: 5,
    pids: [0x172b, 0x1726],
    note: "DPI (preset 1), polling, lift-off distance, sleep timer, and buttons are write-only; battery percentage/charging is read live (no firmware-query command in this protocol). PID 0x172b (wired mode) and 0x1726 (2.4 GHz wireless mode) in SteelSeries Rival 650 Wireless driver" },
  { brand: "SteelSeries", model: "Aerox 3",              status: "supported", req: 13,
    pids: [0x1836],
    note: "Write-only: DPI presets, polling, RGB zones, reactive color, brightness, rainbow, buttons. PID 0x1836 in SteelSeries Aerox 3 driver" },
  { brand: "SteelSeries", model: "Prime+",               status: "supported", req: 12,
    pids: [0x182c],
    note: "Write-only: DPI presets, polling, wheel LED color, brightness, buttons. PID 0x182c in SteelSeries Prime+ driver" },
  { brand: "SteelSeries", model: "Rival 310",            status: "supported", req: 3,
    pids: [0x1720, 0x171e, 0x1736],
    note: "Write-only: DPI (preset 1), polling, logo/wheel LED steady color, buttons; firmware version is read live. PID 0x1720/0x171e (CS:GO Howl Edition)/0x1736 (PUBG Edition) in SteelSeries Rival 310 driver" },
  { brand: "SteelSeries", model: "Prime Mini Wireless",  status: "supported", req: 2,
    pids: [0x184a, 0x1848],
    note: "DPI presets, polling, LED color, sleep/dim timers, default lighting, and buttons are write-only; battery percentage/charging is read live (no firmware-query command in this protocol). PID 0x184a (wired mode) and 0x1848 (2.4 GHz mode) in SteelSeries Prime Mini Wireless driver" },

  // CORSAIR ─────────────────────────────────────────────────────────────
  { brand: "Corsair", model: "NIGHTSWORD RGB",            status: "supported", req: 1,
    pids: [0x1b5c],
    note: "Read-only: identity, firmware, live DPI stages, polling rate, lift-off height, and angle snapping over the 0xffc2/usage-4 feature-report interface (fw 3.41). Close iCUE first — it holds the control interface. PID 0x1b5c in Corsair driver" },
  { brand: "Corsair", model: "Harpoon RGB Pro",           status: "driver",   req: 10,
    note: "iCUE protocol — not implemented" },
  { brand: "Corsair", model: "Katar Pro",                 status: "driver",   req: 12,
    note: "iCUE protocol — not implemented" },
  { brand: "Corsair", model: "M65 Pro RGB",               status: "driver",   req: 10,
    note: "iCUE protocol — not implemented" },
  { brand: "Corsair", model: "Sabre V2 Pro Ultralight",   status: "driver",   req: 8,
    note: "iCUE protocol — not implemented" },
  { brand: "Corsair", model: "Scimitar Elite Wireless SE",status: "driver",   req: 8,
    note: "iCUE protocol — not implemented" },
  { brand: "Corsair", model: "M65 RGB Elite",             status: "driver",   req: 4,
    note: "iCUE protocol — not implemented" },
  { brand: "Corsair", model: "Scimitar RGB Elite",        status: "driver",   req: 5,
    note: "iCUE protocol — not implemented" },
  { brand: "Corsair", model: "Ironclaw RGB",              status: "driver",   req: 5,
    note: "iCUE protocol — not implemented" },

  // GLORIOUS ────────────────────────────────────────────────────────────
  // Three tiers: the Pixart Model O 2 / I 2 family (write-only,
  // drivers/glorious/hid.ts); the pre-Pixart "core1" classic Model O/D/I
  // family (full DPI/polling/LOD/debounce/RGB write + read battery,
  // drivers/glorious/classic-hid.ts, ported from glorious-ctl + mxw); and the
  // newer 8000Hz-class "core2" devices on the SAME classic-hid.ts driver but
  // gated to RGB/debounce/battery only — DPI/polling/LOD stay off for core2
  // because korkje/mxw's own device list never included them, and (for
  // polling specifically) github.com/AMarcinkiewicz/GloriousAutoPollingRate
  // shows the D2 Pro 4K/8K's real polling command uses an entirely different
  // usage page/report layout, confirming core2 isn't just core1 with new
  // values. See [[glorious-classic-protocol]] in project memory for the full
  // writeup, including the exact (unwired) D2 Pro 4K/8K polling-rate bytes.
  { brand: "Glorious", model: "Model O 2 Pro Wireless",  status: "supported", req: 5,
    pids: [0x2033],
    note: "Same PID (0x2033) as the classic driver's \"Model O 2 Wireless\" — Glorious's own \"O2 Pro\" name for it, per AwesomeTy18/GloriousBatteryMonitor's device table. DPI/polling/LOD/debounce/RGB are write-only, battery is read" },
  { brand: "Glorious", model: "Model O",                 status: "supported", req: 54,
    pids: [0x2011, 0x2022],
    note: "Classic driver (VID 0x258a). DPI/polling/LOD/debounce/RGB are write-only, battery is read" },
  { brand: "Glorious", model: "Model D Wireless",        status: "supported", req: 6,
    pids: [0x2012, 0x2023],
    note: "Classic driver (VID 0x258a). DPI/polling/LOD/debounce/RGB are write-only, battery is read. Config collection may be usage 0xffff:0 on newer firmware — the classic driver accepts it" },
  { brand: "Glorious", model: "Model D",                 status: "supported",   req: 8,
    pids: [0x2012],
    note: "Same PID as Model D Wireless's wired mode — classic driver (VID 0x258a)" },
  { brand: "Glorious", model: "Model O2 Pro 4K/8K",     status: "likely",   req: 5,
    pids: [0x201b, 0x2035],
    note: "Classic driver recognizes this PID (VID 0x258a) but only writes RGB/debounce and reads battery — DPI/polling/LOD are unconfirmed on this newer \"core2\" firmware and stay off" },
  { brand: "Glorious", model: "Model O Pro",             status: "supported", req: 1,
    pids: [0x2015, 0x2027],
    note: "Classic driver (VID 0x258a) — full DPI/polling/LOD/debounce/RGB write, battery read, per RealCrystalNight/Glorious-Mouse-Toolkit-Linux's device table" },
  { brand: "Glorious", model: "Model D2 Pro Wireless 8K",status: "likely",  req: 1,
    pids: [0x201c, 0x2036],
    note: "Classic driver recognizes this PID (VID 0x258a) but only writes RGB/debounce and reads battery — DPI/polling/LOD are unconfirmed on this newer \"core2\" firmware and stay off" },
  { brand: "Glorious", model: "Model O3 Wireless",       status: "likely",   req: 5,
    pids: [0xa312, 0xa300],
    note: "8000Hz mouse on VID 0x3794. glorious-ctl's own device list includes it for RGB/debounce/battery, so the classic driver recognizes it for those — DPI/polling/LOD have no confirmed protocol and stay off" },

  // ENDGAME GEAR ────────────────────────────────────────────────────────
  { brand: "Endgame Gear", model: "XM2w 4K",            status: "supported", req: 12,
    note: "egg-we driver (0x3367) covers OP1we/XM2we family" },
  { brand: "Endgame Gear", model: "OP1we",            status: "supported", req: 1,
    pids: [0x1961, 0x1962],
    note: "egg-we driver (0x3367) covers OP1we/XM2we family" },
  { brand: "Endgame Gear", model: "OP1w 4K v2",         status: "likely",    req: 17,
    note: "egg-we driver (0x3367) covers OP1we/XM2we family — needs hardware test" },
  { brand: "Endgame Gear", model: "OP1 8K",             status: "supported", req: 1,
    pids: [0x1964, 0x1976, 0x1978],
    note: "Egg OP1 driver — PIDs 0x1964/0x1976/0x1978" },
  { brand: "Endgame Gear", model: "XM2 8K",             status: "supported", req: 1,
    pids: [0x1966, 0x1980],
    note: "Egg OP1 driver — PIDs 0x1966/0x1980" },

  // ATK / VGN ───────────────────────────────────────────────────────────
  { brand: "ATK", model: "F1 V2 Ultra Max",             status: "supported", req: 1,
    note: "ATK vendor (0x373b, usagePage 0xff02) covered" },
  { brand: "ATK", model: "VXE Dragonfly R1 Pro",        status: "likely",    req: 10,
    note: "VGN F2 driver (0xfb56/0xfb57) covers Dragonfly F2; R1 Pro needs test" },
  { brand: "VXE", model: "R1 Pro Max",                  status: "supported", req: 6,
    pids: [0xf58a, 0xf58c],
    note: "ATK firmware device id 2,27 (PAW3395) verified — COMPX PIDs 0xf58c (wired) / 0xf58a (receiver) in the ATK R1 driver" },
  { brand: "VXE", model: "R1 (SE)",                     status: "likely",    req: 9,
    note: "ATK firmware device id 2,11/2,12 — shares the R1 SE+ COMPX transports; not confirmed on hardware" },
  { brand: "VXE", model: "R1 SE+",                      status: "supported", req: 9,
    pids: [0xf58e, 0xf58f],
    note: "Wired 0x3554:0xf58f identity, settings, profiles, and button inspection verified through Chromium WebHID. Wireless identity and receiver telemetry verified through the 0x3554:0xf58e 1K receiver" },
  { brand: "ATK", model: "X1 V2 Ultimate",              status: "likely",    req: 4,
    note: "ATK driver (0x373b) likely covers — needs hardware test" },
  { brand: "ATK", model: "A9 Air",                      status: "likely",    req: 4,
    note: "ATK driver (0x373b) likely covers — needs hardware test" },
  { brand: "ATK", model: "F1 Ultimate",                 status: "likely",    req: 1,
    note: "ATK driver (0x373b) likely covers — needs hardware test" },
  { brand: "ATK", model: "F1 Ultimate 2.0",             status: "likely",      req: 0,
    note: "ATK firmware device id 1,8 — PAW3950Ultra, not yet verified on hardware" },
  { brand: "ATK", model: "A9 Mini +",                    status: "likely",      req: 0,
    note: "ATK firmware device id 1,31/1,52 — PAW3955Master, not yet verified on hardware" },
  { brand: "ATK", model: "VXE Mad R Major",             status: "likely",    req: 6,
    note: "ATK driver (0x373b) likely covers — needs hardware test" },
  { brand: "ATK", model: "ZERO",                        status: "supported", req: 1,
    pids: [0x1154, 0x1155],
    note: "BITMOUSE driver — wired 0x1154, 8K receiver 0x1155, usagePage 0xff05. Verified on hardware: DPI, poll rate, debounce, sleep, motion sync, ripple. Lift-off not decoded" },
  { brand: "ATK", model: "VXE Zero Normal",             status: "likely",    req: 4,
    note: "The 0xff02 ATK driver does not reach the ZERO family — it uses the BITMOUSE channel on 0xff05; needs its own PID confirmed on hardware" },
  { brand: "VGN", model: "Dragonfly F2 Master+",        status: "supported", req: 1,
    pids: [0xfb56, 0xfb57],
    note: "VGN F2 driver — PIDs 0xfb56/0xfb57" },

  // WLMouse ─────────────────────────────────────────────────────────────
  { brand: "WLMouse", model: "Beast X",                 status: "supported", req: 3,
    pids: [0xa883, 0xa884],
    note: "PIDs 0xa883 / 0xa884 already in WLMouse driver" },
  { brand: "WLMouse", model: "Beast Mini",              status: "supported", req: 1,
    pids: [0xa885, 0xa886],
    note: "PIDs 0xa885 / 0xa886 in WLMouse driver" },
  { brand: "WLMouse", model: "Beast X Pro",             status: "supported", req: 1,
    pids: [0xa870, 0xa871],
    note: "PIDs 0xa870 / 0xa871 in WLMouse driver" },
  { brand: "WLMouse", model: "Sword X",                 status: "supported", req: 1,
    pids: [0xa878, 0xa879],
    note: "PIDs 0xa878 / 0xa879 in WLMouse driver" },
  { brand: "WLMouse", model: "Beast Max",               status: "supported", req: 1,
    pids: [0xa880, 0xa881],
    note: "PIDs 0xa880 / 0xa881 in WLMouse driver" },

  // PULSAR ──────────────────────────────────────────────────────────────
  { brand: "Pulsar", model: "Tenz Signature",           status: "supported", req: 9,
    note: "Pulsar driver (VID 0x3710) — collection-based detection" },
  { brand: "Pulsar", model: "X2h",                      status: "supported", req: 6,
    note: "Pulsar driver (VID 0x3710) — collection-based detection" },
  { brand: "Pulsar", model: "X2 V3 ES Mini",            status: "supported", req: 3,
    note: "Pulsar driver (VID 0x3710) — collection-based detection" },
  { brand: "Pulsar", model: "X3 Medium",                status: "supported", req: 5,
    pids: [0x3409, 0x3410, 0x5402, 0x5403],
    note: "XS-1 feature-report driver (usage 0xffff:1) — PIDs pinned in the protocol registry" },
  { brand: "Pulsar", model: "X2F",                      status: "supported", req: 2,
    note: "Pulsar driver (VID 0x3710) — collection-based detection" },

  // VAXEE ───────────────────────────────────────────────────────────────
  // All models share the same report-0x0e feature-report protocol on VID
  // 0x3057; the USB product id identifies the model (src/vaxee).
  { brand: "VAXEE", model: "XE Wireless",               status: "supported", req: 0,
    pids: [0x1003],
    note: "PID 0x1003 in the VAXEE catalog (VID 0x3057)" },
  { brand: "VAXEE", model: "NP-01S Wireless",           status: "supported", req: 0,
    pids: [0x1004],
    note: "PID 0x1004 in the VAXEE catalog (VID 0x3057)" },
  { brand: "VAXEE", model: "AX Wireless",               status: "supported", req: 2,
    pids: [0x1005],
    note: "PID 0x1005 in the VAXEE catalog (VID 0x3057)" },
  { brand: "VAXEE", model: "NP-01 Wireless",            status: "supported", req: 0,
    pids: [0x1006],
    note: "PID 0x1006 in the VAXEE catalog (VID 0x3057)" },
  { brand: "VAXEE", model: "XE-S Wireless",             status: "supported", req: 0,
    pids: [0x1007],
    note: "PID 0x1007 in the VAXEE catalog (VID 0x3057)" },
  { brand: "VAXEE", model: "XE-S-L Wireless",           status: "supported", req: 0,
    pids: [0x1008],
    note: "PID 0x1008 in the VAXEE catalog (VID 0x3057)" },
  { brand: "VAXEE", model: "VAXEE x Ninjutso Sora",     status: "supported", req: 0,
    pids: [0x1009],
    note: "PID 0x1009 in the VAXEE catalog (VID 0x3057)" },
  { brand: "VAXEE", model: "E1 Wireless",               status: "supported", req: 0,
    pids: [0x1010],
    note: "PID 0x1010 in the VAXEE catalog (VID 0x3057)" },
  { brand: "VAXEE", model: "NP-01S V2 Wireless",        status: "supported", req: 0,
    pids: [0x1011],
    note: "PID 0x1011 in the VAXEE catalog (VID 0x3057)" },
  { brand: "VAXEE", model: "XE V2 Wireless",            status: "supported", req: 0,
    pids: [0x1012],
    note: "PID 0x1012 in the VAXEE catalog (VID 0x3057)" },
  { brand: "VAXEE", model: "NP-01S Ergo Wireless",      status: "supported", req: 0,
    pids: [0x1013],
    note: "PID 0x1013 in the VAXEE catalog (VID 0x3057)" },
  { brand: "VAXEE", model: "NP-01S V3 Wireless",        status: "supported", req: 0,
    pids: [0x1014],
    note: "PID 0x1014 in the VAXEE catalog (VID 0x3057)" },
  { brand: "VAXEE", model: "NP-01 Ergo Wireless",       status: "supported", req: 0,
    pids: [0x1015],
    note: "PID 0x1015 in the VAXEE catalog (VID 0x3057)" },

  // LAMZU / CRDRAKO ─────────────────────────────────────────────────────
  { brand: "Lamzu", model: "Maya X",                    status: "supported", req: 1,
    pids: [0x001c, 0x001d, 0x001e],
    note: "PIDs 0x001c/0x001d/0x001e in Lamzu driver" },
  { brand: "Lamzu", model: "Inca",                      status: "supported", req: 3,
    pids: [0x0009, 0x000f, 0x0010],
    note: "Enumerates under Lamzu's own VID 0x37b0 — wired 0x0009 and 8K receiver 0x0010 confirmed on hardware; 1K receiver 0x000f untested" },
  { brand: "Lamzu", model: "Atlantis (shared family ids)", status: "likely", req: 1,
    pids: [0xf50f],
    note: "OG V2 / Mini / Mini Pro / Thorn / Maya / Paro share 0xf50f on the cable and cannot be told apart on the wire; 0xf50f verified, the 0xf50d/0xf510/0xf517 receivers unverified" },
  { brand: "Lamzu", model: "Thorn",                     status: "quickwin",  req: 4,
    note: "CompX protocol implemented; Thorn PID not yet in driver" },
  { brand: "CRDRAKO", model: "KO-ONE",                  status: "supported", req: 1,
    pids: [0x006a, 0x006b],
    note: "PIDs 0x006a/0x006b in Lamzu/CompX driver" },

  // NINJUTSO ────────────────────────────────────────────────────────────
  { brand: "Ninjutso", model: "Sora V2",                status: "supported", req: 1,
    pids: [0xae11, 0xae12, 0xae13, 0xae14, 0xae15, 0xae16],
    note: "Legacy 0x1915 PIDs in Ninjutso driver" },
  { brand: "Ninjutso", model: "Sora V3",                status: "supported", req: 1,
    pids: [0xe010],
    note: "PID 0xe010 in Ninjutso driver" },
  { brand: "Ninjutso", model: "TEN",                    status: "supported", req: 1,
    pids: [0xe020, 0xea01],
    note: "PIDs 0xe020/0xea01 in Ninjutso driver" },
  { brand: "Ninjutso", model: "Sora",                   status: "likely",    req: 5,
    note: "Driver covers Sora V2/V3; original Sora PID not listed — needs test" },

  // TEEVOLUTION ─────────────────────────────────────────────────────────
  { brand: "Teevolution", model: "Terra Pro",           status: "supported", req: 1,
    pids: [0xf520, 0xf523, 0xf5bb, 0xf522],
    note: "PIDs 0xf520/0xf523/0xf5bb/0xf522 in Teevolution driver" },

  // WALLHACK ─────────────────────────────────────
  { brand: "WALLHACK", model: "M-001",                  status: "supported", req: 1,
    pids: [0x1110, 0x0807],
    note: "Full read/write: DPI, polling, LOD, processing, battery. PIDs 0x1110 (0x0807 demo) in WALLHACK mouse driver" },

  // FINALMOUSE ──────────────────────────────────────────────────────────
  { brand: "Finalmouse", model: "Starlight-12 / ULX",   status: "supported", req: 1,
    pids: [0x0100],
    note: "ULX dongle PID 0x0100 in Finalmouse driver" },

  // ZAUNKOENIG ──────────────────────────────────────────────────────────
  { brand: "Zaunkoenig", model: "M3K",                  status: "supported", req: 1,
    pids: [0xa462],
    note: "PID 0xa462 in Zaunkoenig driver" },
  { brand: "Zaunkoenig", model: "M2K",                  status: "supported", req: 1,
    pids: [0xa3cf],
    note: "PID 0xa3cf in Zaunkoenig driver" },

  // MODDO / ORBITAL ─────────────────────────────────────────────────────
  { brand: "moddoMOUSE", model: "moddoMOUSE",           status: "supported", req: 1,
    note: "Vendor config interface (0x2fe3) in moddo driver" },
  { brand: "Orbital", model: "Ghost / Pathfinder V2",   status: "supported", req: 1,
    pids: [0x080c],
    note: "PID 0x080c in Orbital driver" },

  // MICROSOFT ───────────────────────────────────────────────────────────
  { brand: "Microsoft", model: "Pro Intellimouse",      status: "supported", req: 0,
    pids: [0x082a],
    note: "For LOD, Low is 2mm, High is 3mm. Calibrated surface 1/2/3 is not supported yet. On Windows, reading device status requires the Desktop App or OpenMouse Bridge companion." },
  { brand: "Microsoft", model: "Classic Intellimouse",  status: "supported", req: 0,
    pids: [0x0823],
    note: "DPI configuration only. On Windows, reading device status requires the Desktop App or OpenMouse Bridge companion." },

  // KEYCHRON ────────────────────────────────────────────────────────────
  { brand: "Keychron", model: "Nape Pro",               status: "supported", req: 1,
    pids: [0x0440],
    note: "PID 0x0440 in Keychron driver" },
  { brand: "Keychron", model: "M6",                     status: "supported", req: 1,
    pids: [0xd060, 0xd029],
    note: "Wired and Link-KM 2.4 GHz. DPI stages, polling, lift-off, motion sync, angle snapping, ripple control, angle tuning, debounce, sleep, onboard profiles and battery. No Bluetooth control channel." },

  // Asus ────────────────────────────────────────────────────────────────
  { brand: "Asus",     model: "Harpe Ace Aim Lab",      status: "driver",    req: 10,
    note: "Armoury Crate protocol — not implemented" },
  { brand: "Asus",     model: "TUF Gaming M5",          status: "driver",    req: 2,
    note: "Armoury Crate protocol — not implemented" },
  { brand: "Asus",     model: "Gladius II Core",        status: "driver",    req: 1,
    note: "Armoury Crate protocol — not implemented" },
  { brand: "Asus",     model: "Strix Impact III",       status: "driver",    req: 3,
    note: "Armoury Crate protocol — not implemented" },
  { brand: "Asus",     model: "TUF Gaming M3 Gen 1",    status: "driver",    req: 2,
    note: "Armoury Crate protocol — not implemented" },
  // The Gladius II P502 is the one Asus mouse the protocol drives (src/asus,
  // VID 0x0b05); the Armoury Crate models above are unaffected.
  { brand: "Asus",     model: "ROG Gladius II P502",    status: "supported", req: 1,
    pids: [0x1845],
    note: "PID 0x1845 (VID 0x0b05) in the Gladius II driver — DPI, polling, debounce, LOD, profiles and RGB" },

  // INCOTT ──────────────────────────────────────────────────────────────
  // Every Incott model enumerates under the same two product ids — 093A:522C
  // on the 2.4 GHz dongle, 093A:622C wired — so the USB id cannot tell the
  // models apart. The driver reads the model and the fitted sensor out of the
  // device's own identity reply instead, which is why only the one that was
  // tested on hardware claims full support.
  { brand: "Incott",        model: "G23 V2 (SE / Pro)",  status: "supported", req: 3,
    note: "Hardware-verified: DPI stages, polling, buttons, per-axis DPI, lift-off, rapid fire, macros. Also written G23V2",
    pids: [0x522c, 0x622c] },
  { brand: "Incott",        model: "GHERO (and Pro)",    status: "likely",    req: 0,
    note: "Same driver, protocol and product ids as the G23 V2; not confirmed on hardware" },
  { brand: "Incott",        model: "G23 (and Pro)",      status: "likely",    req: 0,
    note: "Same driver, protocol and product ids as the G23 V2; not confirmed on hardware" },
  { brand: "Incott",        model: "G24 (and Pro)",      status: "likely",    req: 0,
    note: "Same driver, protocol and product ids as the G23 V2; not confirmed on hardware" },
  { brand: "Incott",        model: "Zero 29 (and Pro)",  status: "likely",    req: 0,
    note: "Also sold as 029. Same driver, protocol and product ids as the G23 V2; not confirmed on hardware" },
  { brand: "Incott",        model: "Zero 39 (and Pro)",  status: "likely",    req: 0,
    note: "Also sold as 039. Same driver, protocol and product ids as the G23 V2; not confirmed on hardware" },

  // RAWM ────────────────────────────────────────────────────────────────
  // RAWM HUB driver identities — every entry below is verified on hardware
  // (src/rawm); the 0x232a/0x232b/0x2335/0x2336 receivers are excluded as
  // they are not mice.
  { brand: "RAWM",          model: "Blade 1",            status: "supported", req: 0,
    pids: [0x2328],
    note: "PID 0x2328 in RAWM driver — verified on hardware" },
  { brand: "RAWM",          model: "ML01",               status: "supported", req: 0,
    pids: [0x2329],
    note: "PID 0x2329 in RAWM driver — verified on hardware" },
  { brand: "RAWM",          model: "MH01",               status: "supported", req: 0,
    pids: [0x232c],
    note: "PID 0x232c in RAWM driver — verified on hardware" },
  { brand: "RAWM",          model: "SL01",               status: "supported", req: 0,
    pids: [0x232d],
    note: "PID 0x232d in RAWM driver — verified on hardware" },
  { brand: "RAWM",          model: "SH01",               status: "supported", req: 0,
    pids: [0x232e, 0x232f],
    note: "PIDs 0x232e/0x232f in RAWM driver — verified on hardware" },
  { brand: "RAWM",          model: "SH01 Pro",           status: "supported", req: 0,
    pids: [0x2330, 0x2332],
    note: "PIDs 0x2330/0x2332 in RAWM driver — verified on hardware" },
  { brand: "RAWM",          model: "MH01 Pro",           status: "supported", req: 1,
    pids: [0x2331],
    note: "PID 0x2331 in RAWM driver — verified on hardware" },
  { brand: "RAWM",          model: "ES21",               status: "supported", req: 0,
    pids: [0x2333],
    note: "PID 0x2333 in RAWM driver — verified on hardware" },
  { brand: "RAWM",          model: "ES21 Pro",           status: "supported", req: 0,
    pids: [0x2334],
    note: "PID 0x2334 in RAWM driver — verified on hardware" },
  { brand: "RAWM",          model: "ES21M",              status: "supported", req: 0,
    pids: [0x2337],
    note: "PID 0x2337 in RAWM driver — verified on hardware" },
  { brand: "RAWM",          model: "ER21 Pro",           status: "supported", req: 0,
    pids: [0x2338],
    note: "PID 0x2338 in RAWM driver — verified on hardware" },
  { brand: "RAWM",          model: "ER21M",              status: "supported", req: 0,
    pids: [0x2339],
    note: "PID 0x2339 in RAWM driver — verified on hardware" },

  // OTHER DRIVER-NEEDED ─────────────────────────────────────────────────
  { brand: "Bloody",        model: "Max W95",           status: "driver",    req: 3,
    note: "A4tech / Bloody protocol — not implemented" },
  { brand: "Fantech",       model: "THOR II X16",       status: "driver",    req: 1,
    note: "Fantech protocol — not implemented" },
  // Fantech WG14P is auto-listed from the @openmouse/protocol driver registry.
  { brand: "Cooler Master", model: "MasterMouse MM720", status: "driver",    req: 3,
    note: "CM protocol — not implemented" },
  { brand: "Cooler Master", model: "MM711",             status: "driver",    req: 5,
    note: "CM protocol — not implemented" },
  { brand: "K-snake",     model: "X11",               status: "supported", req: 1,
    pids: [0x2255],
    note: "VID 0xA8A4 (USB) / 0xA8A5 (2.4G) PID 0x2255 — 0x55-framed output-report protocol, verified on retail dongle hardware (FW 2.1.7)" },

  // UNKNOWNS ────────────────────────────────────────────────────────────
  { brand: "Hitscan",       model: "Hyperlight",        status: "unknown",   req: 17,
    note: "Protocol unknown — HID capture needed" },
  { brand: "RAWM",          model: "Leviathan V4",      status: "unknown",   req: 10,
    note: "Protocol unknown" },
  { brand: "AJAZZ",         model: "AJ159 Apex",        status: "unknown",   req: 10,
    note: "Protocol unknown" },
  { brand: "Furycube",      model: "G11",               status: "unknown",   req: 8,
    note: "Protocol unknown" },
  { brand: "Mchose",        model: "A7 V2 Ultra+",      status: "supported", req: 3,
    pids: [0x4021, 0x100b],
    note: "Confirmed on hardware over both the 2.4 GHz receiver and the cable — model, firmware, battery and charge state, DPI stages and values, stage count, polling, lift-off, motion sync, ripple, angle snapping, angle tuning, performance mode, debounce, sleep, 3 named profiles and button remapping all round-tripped" },
  { brand: "Mchose",        model: "MagDock (charging base)", status: "supported", req: 0,
    pids: [0x1012],
    note: "The A7 V2 base, not a mouse -- RGB read and write confirmed on hardware; the mice themselves have no LEDs" },
  { brand: "Mchose",        model: "A7 V2 Ultra",       status: "likely",    req: 3,
    note: "Same driver and protocol as the Ultra+; not confirmed on hardware" },
  { brand: "Mchose",        model: "A7 V2 Pro+",        status: "likely",    req: 0,
    note: "Same driver and protocol as the Ultra+; not confirmed on hardware" },
  { brand: "Mchose",        model: "A7 V2 Pro",         status: "likely",    req: 0,
    note: "Same driver and protocol as the Ultra+; not confirmed on hardware" },
  // The V3 generation is a different protocol on the same usage page, driven
  // read-only until someone with the hardware can time and verify the writes.
  { brand: "Mchose",        model: "A7 V3 Ultra+",      status: "likely",    req: 0,
    pids: [0x4033, 0x1014, 0x1018],
    note: "Separate driver from the V2 -- reads model, battery, DPI stages, polling, lift-off, processing, profile and buttons. Read-only and untested: the protocol comes from MCHOSE's own software, not from hardware" },
  { brand: "Mchose",        model: "A7 V3 Pro+",        status: "likely",    req: 0,
    pids: [0x4032],
    note: "Same read-only V3 driver as the A7 V3 Ultra+; not confirmed on hardware" },
  { brand: "Mchose",        model: "A7 V3 Pro",         status: "likely",    req: 0,
    pids: [0x4031],
    note: "Same read-only V3 driver as the A7 V3 Ultra+; not confirmed on hardware" },
  { brand: "Mchose",        model: "A7 V3",             status: "likely",    req: 0,
    pids: [0x4030],
    note: "Same read-only V3 driver as the A7 V3 Ultra+; not confirmed on hardware" },
  // The A5 Pro Max runs a separate first-generation protocol from the A7 HUB
  // family (src/mchose/a5-gen1.ts).
  { brand: "Mchose",        model: "A5 Pro Max",        status: "supported", req: 0,
    pids: [0xf019, 0xf013, 0xf015],
    note: "Wired 0xf019 and 1K receiver 0xf013 verified on hardware; 4K receiver 0xf015 untested" },
  { brand: "Mchose",        model: "K7 Ultra",          status: "unknown",   req: 9,
    note: "Protocol unknown" },
  { brand: "Mchose",        model: "L7 Ultra+",         status: "unknown",   req: 81,
    note: "Protocol unknown" },
  { brand: "G-Wolves",      model: "HTX Mini 8K",       status: "unknown",   req: 4,
    note: "Protocol unknown" },
  { brand: "Angry Miao",    model: "Infinity .97",      status: "unknown",   req: 7,
    note: "Protocol unknown" },
  { brand: "Dark Project",  model: "Novus SE",          status: "unknown",   req: 2,
    note: "Protocol unknown — HID capture needed" },
  { brand: "Scyrox",        model: "V8",                status: "unknown",   req: 11,
    note: "Protocol unknown" },
  { brand: "Mchose",        model: "AX5",               status: "unknown",   req: 3,
    note: "Protocol unknown" },
  { brand: "AJAZZ",         model: "AJ139 Pro",         status: "unknown",   req: 4,
    note: "Protocol unknown" },
  { brand: "AJAZZ",         model: "AJ199",             status: "unknown",   req: 8,
    note: "Protocol unknown" },
  { brand: "Gravastar",     model: "Mercury X Pro",     status: "unknown",   req: 5,
    note: "Protocol unknown" },
  { brand: "Gravastar",     model: "M1",                status: "unknown",   req: 3,
    note: "Protocol unknown" },
  { brand: "Gravastar",     model: "M2",                status: "unknown",   req: 4,
    note: "Protocol unknown" },
  { brand: "G-Wolves",      model: "HT-M-H ACE Wireless",status: "unknown", req: 1,
    note: "Protocol unknown" },
  { brand: "Angry Miao",    model: "Infinity Mouse",    status: "unknown",   req: 3,
    note: "Protocol unknown" },
  { brand: "VortexSeries",  model: "IGNIX F3",          status: "unknown",   req: 3,
    note: "Protocol unknown" },
  { brand: "Darmoshark",    model: "M3S",               status: "unknown",   req: 1,
    note: "Protocol unknown" },
  { brand: "Swiftpoint",    model: "Z2",                status: "unknown",   req: 1,
    note: "Has own software — complex macro/haptics protocol" },
  { brand: "Swiftpoint",    model: "Z3",                status: "unknown",   req: 1,
    note: "Has own software — complex macro/haptics protocol" },
  { brand: "Kreo",          model: "Chimera V2 Wireless",status: "unknown",  req: 1,
    note: "Protocol unknown" },
  { brand: "Kreo",          model: "Harpy",             status: "unknown",   req: 6,
    note: "Protocol unknown" },
  { brand: "ipi",           model: "Float 3950",        status: "unknown",   req: 2,
    note: "Protocol unknown" },
  { brand: "Solakaka",      model: "SM802 Pro",         status: "unknown",   req: 1,
    note: "Has its own web configurator" },
  { brand: "E-YOOSO",       model: "X-44 Lite",         status: "unknown",   req: 1,
    note: "Protocol unknown" },
  { brand: "HAVIT",         model: "Gamenote",          status: "unknown",   req: 1,
    note: "Protocol unknown" },
  { brand: "Empire Gaming", model: "RF906 Wireless",    status: "unknown",   req: 1,
    note: "Protocol unknown" },
  { brand: "DeadSkull",     model: "Orbit Wired",       status: "unknown",   req: 1,
    note: "Protocol unknown" },
  { brand: "ISY",           model: "IGM-6000",          status: "unknown",   req: 1,
    note: "Protocol unknown" },

  // COMMUNITY REQUESTS ─────────────────────────────────────────────────
  // Imported from the Supabase request catalog on 2026-09-24, when the site
  // moved off Supabase. Duplicates were merged into the rows above, names
  // were tidied, and non-mice were dropped. Vote counts are frozen here.
  { brand: "2E Gaming", model: "MG355 WL", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Acer", model: "OMW950", status: "pending", req: 2,
    note: "Not sure · DPI · Polling rate · Buttons · Lighting" },
  { brand: "Acer", model: "Predator Cestus 353", status: "pending", req: 2,
    note: "Wireless USB receiver" },
  { brand: "Acer", model: "Easy Fit", status: "pending", req: 1,
    note: "Wireless USB receiver" },
  { brand: "Acer", model: "Nitro", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "Acer", model: "Wireless Optical", status: "pending", req: 1,
    note: "Wireless USB receiver" },
  { brand: "AJAZZ", model: "AJ139 V2 MC", status: "pending", req: 8,
    note: "Wired and wireless" },
  { brand: "AJAZZ", model: "AJ159 Pro", status: "pending", req: 5,
    note: "Wired and wireless" },
  { brand: "AJAZZ", model: "AJ179 Pro", status: "pending", req: 4,
    note: "Wired and wireless" },
  { brand: "AJAZZ", model: "AJ159P MC", status: "pending", req: 3,
    note: "Wired and wireless" },
  { brand: "AJAZZ", model: "AM3 Max", status: "pending", req: 3,
    note: "Wired and wireless" },
  { brand: "AJAZZ", model: "NJ08", status: "pending", req: 3,
    note: "Wired and wireless" },
  { brand: "AJAZZ", model: "AJ159 V2 MC", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "AJAZZ", model: "NJ07", status: "pending", req: 0,
    note: "Wired and wireless" },
  { brand: "Alienware", model: "AW610M", status: "pending", req: 3,
    note: "Wired and wireless" },
  { brand: "Amkette", model: "XS Series Flow Plus", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Andowl", model: "Q-144", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "Ant Esports", model: "GM320", status: "pending", req: 2,
    note: "Wired USB" },
  { brand: "Ant Esports", model: "GM40", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "AQIRYS", model: "NYX", status: "pending", req: 2,
    note: "Wired and wireless" },
  { brand: "Arbiter Studio", model: "Akitsu Carbon Fiber 8K", status: "pending", req: 3,
    note: "Wireless USB receiver" },
  { brand: "Armaggeddon", model: "Textron Scorpion 7", status: "pending", req: 0,
    note: "Wired USB" },
  { brand: "Asus", model: "ROG Harpe Ace Mini", status: "pending", req: 2,
    note: "Wireless USB receiver" },
  { brand: "Asus", model: "P513", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Asus", model: "P709", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Asus", model: "ROG Harpe II Ace", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Asus", model: "ROG Keris Wireless AimPoint", status: "pending", req: 0,
    note: "Wired and wireless" },
  { brand: "ATK", model: "A9", status: "pending", req: 3,
    note: "Wireless USB receiver" },
  { brand: "ATK", model: "A9 Ultimate+", status: "pending", req: 3,
    note: "Wired and wireless" },
  { brand: "ATK", model: "G3 Pro", status: "pending", req: 2,
    note: "Wired and wireless" },
  { brand: "ATK", model: "Blazing Sky X1 Pro", status: "pending", req: 1,
    note: "Not sure" },
  { brand: "ATK", model: "Ghost", status: "pending", req: 1,
    note: "Wireless USB receiver" },
  { brand: "ATK", model: "VXE Mad R Major+", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "ATK", model: "X3", status: "pending", req: 1,
    note: "Not sure" },
  { brand: "ATK", model: "X1", status: "pending", req: 0,
    note: "Wired and wireless" },
  { brand: "Attack Shark", model: "X3 Max", status: "pending", req: 5,
    note: "Wired and wireless" },
  { brand: "Attack Shark", model: "G3 Pro", status: "pending", req: 2,
    note: "Wired and wireless" },
  { brand: "Attack Shark", model: "V6", status: "pending", req: 2,
    note: "Wired and wireless" },
  { brand: "Attack Shark", model: "X11 Ultra", status: "pending", req: 2,
    note: "Wired and wireless" },
  { brand: "Attack Shark", model: "R11 Ultra", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Attack Shark", model: "V3", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Attack Shark", model: "X2", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Attack Shark", model: "X5", status: "pending", req: 0,
    note: "Bluetooth" },
  { brand: "Aula", model: "SC900 Pro", status: "pending", req: 3,
    note: "Wireless USB receiver" },
  { brand: "Aula", model: "SC620", status: "pending", req: 2,
    note: "Wired and wireless" },
  { brand: "Aula", model: "SC380 Pro", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Aula", model: "SC680", status: "pending", req: 0,
    note: "Wireless USB receiver" },
  { brand: "Baracuda", model: "BGM-121", status: "pending", req: 0,
    note: "Wireless USB receiver" },
  { brand: "Battletron", model: "3218230", status: "pending", req: 3,
    note: "Wired USB" },
  { brand: "Bloody", model: "A70", status: "pending", req: 4,
    note: "Wired USB" },
  { brand: "Bloody", model: "ES7", status: "pending", req: 3,
    note: "Wired USB" },
  { brand: "Bloody", model: "P90 Pro", status: "pending", req: 2,
    note: "Wired USB" },
  { brand: "Bloody", model: "X5MAX", status: "pending", req: 2,
    note: "Wired USB" },
  { brand: "Bloody", model: "J90S", status: "pending", req: 0,
    note: "Wired USB" },
  { brand: "Cepter", model: "Falco", status: "pending", req: 0,
    note: "Wireless USB receiver" },
  { brand: "Cepter", model: "Falco Pro", status: "pending", req: 0,
    note: "Wired and wireless" },
  { brand: "Cooler Master", model: "MM310 (SF6 Chun-Li)", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "Cooler Master", model: "MM730", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "Corsair", model: "Harpoon RGB Wireless", status: "pending", req: 12,
    note: "Wired and wireless" },
  { brand: "Corsair", model: "Sabre RGB Pro Champion Series", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "Cosmic Byte", model: "Firestorm", status: "pending", req: 2,
    note: "Wired USB" },
  { brand: "Cosmic Byte", model: "Kilonova 3389IC", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Cosmic Byte", model: "Raptor", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "CyberPower", model: "MO-131-302", status: "pending", req: 4,
    note: "Wired USB" },
  { brand: "Dareu", model: "EM901", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Dark Project", model: "Nexus", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Dark Project", model: "Novus Pro", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "DarkFlash", model: "DFM80", status: "pending", req: 0,
    note: "Wired and wireless" },
  { brand: "Darmoshark", model: "M3", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Darmoshark", model: "M3 4K", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Darmoshark", model: "M3 Pro", status: "pending", req: 1,
    note: "Wireless USB receiver" },
  { brand: "Darmoshark", model: "M5 V2", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Dell", model: "MS116", status: "pending", req: 2,
    note: "Wired USB" },
  { brand: "Dell", model: "MS900", status: "pending", req: 2,
    note: "Wired and wireless" },
  { brand: "Delux", model: "M900 Pro", status: "pending", req: 4,
    note: "Wireless USB receiver" },
  { brand: "Delux", model: "M700 Ultra", status: "pending", req: 2,
    note: "Wired and wireless" },
  { brand: "Delux", model: "Seeker M618XSD", status: "pending", req: 2,
    note: "Wired and wireless" },
  { brand: "Delux", model: "M900 Mini", status: "pending", req: 0,
    note: "Wired and wireless" },
  { brand: "DEVO", model: "Solis Black", status: "pending", req: 0,
    note: "Wired and wireless" },
  { brand: "DEXP", model: "DGSAdept 66662", status: "pending", req: 1,
    note: "Not sure" },
  { brand: "Drakar", model: "Asgard", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Dune Voyager", model: "DV-GE4", status: "pending", req: 9,
    note: "Wired USB" },
  { brand: "Endgame Gear", model: "OP1 8K V2", status: "pending", req: 3,
    note: "Wired USB" },
  { brand: "Endgame Gear", model: "OP1w 4K", status: "pending", req: 3,
    note: "Wired and wireless" },
  { brand: "Endgame Gear", model: "XM1r", status: "pending", req: 2,
    note: "Wired USB" },
  { brand: "Endgame Gear", model: "XM2w 4K V2", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Endgame Gear", model: "OP1 RGB", status: "pending", req: 0,
    note: "Wired USB" },
  { brand: "Endorfy", model: "EY6A016", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Epomaker", model: "NEX Lite", status: "pending", req: 2,
    note: "Wired and wireless" },
  { brand: "Epomaker", model: "Carbon X", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "EVGA", model: "X12", status: "pending", req: 0,
    note: "Wired USB" },
  { brand: "Evofox", model: "Shadow X Pro", status: "pending", req: 3,
    note: "Wired and wireless" },
  { brand: "Evofox", model: "Banshee 3", status: "pending", req: 2,
    note: "Wired and wireless" },
  { brand: "Evofox", model: "Banshee", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Evofox", model: "Blaze", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "EWEADN", model: "S9 Ultra", status: "pending", req: 2,
    note: "Wired and wireless" },
  { brand: "EWEADN", model: "GS01", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "EWEADN", model: "L1", status: "pending", req: 0,
    note: "Wired and wireless" },
  { brand: "EWEADN", model: "S9 Pro", status: "pending", req: 0,
    note: "Wired and wireless" },
  { brand: "Fantech", model: "Crypto II VX7V2", status: "pending", req: 4,
    note: "Wired and wireless" },
  { brand: "Fantech", model: "X9 Thor", status: "pending", req: 3,
    note: "Wired USB" },
  { brand: "Fantech", model: "Phantom II VX6", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "Fantech", model: "Venom I WGC", status: "pending", req: 1,
    note: "Wireless USB receiver" },
  { brand: "Fantech", model: "Venom II WGC2", status: "pending", req: 1,
    note: "Wireless USB receiver" },
  { brand: "Fantech", model: "Zeus X5s", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "Finalmouse", model: "Starlight Pro Tenz", status: "pending", req: 1,
    note: "Wireless USB receiver" },
  { brand: "Finalmouse", model: "UltraX", status: "pending", req: 1,
    note: "Wireless USB receiver" },
  { brand: "Fnatic", model: "Bolt", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Furycube", model: "G13 Pro", status: "pending", req: 3,
    note: "Wired and wireless" },
  { brand: "G-Wolves", model: "Lycan 8K", status: "pending", req: 6,
    note: "Wired and wireless" },
  { brand: "G-Wolves", model: "WARG", status: "pending", req: 2,
    note: "Wired and wireless" },
  { brand: "G-Wolves", model: "Fenrir Asym", status: "pending", req: 0,
    note: "Wireless USB receiver" },
  { brand: "Gamen", model: "GM1200", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "Garuda Gear", model: "Hawk 1", status: "pending", req: 0,
    note: "Not sure" },
  { brand: "Genesis", model: "Krypton 555", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "Genesis", model: "Krypton 750", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "Genesis", model: "Zircon XIII", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Genesis", model: "Krypton 290", status: "pending", req: 0,
    note: "Wired USB" },
  { brand: "Gigabyte", model: "Aorus M5", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "Gigabyte", model: "Aorus M6", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Glorious", model: "Model D 2 Wireless", status: "pending", req: 1,
    note: "Wireless USB receiver" },
  { brand: "Glorious", model: "Model D-", status: "pending", req: 0,
    note: "Wired and wireless" },
  { brand: "Hator", model: "Pulsar 3 Ultra 4K Wireless", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "HAVIT", model: "MS1035", status: "pending", req: 2,
    note: "Wired USB" },
  { brand: "HAVIT", model: "MS974WB", status: "pending", req: 2,
    note: "Wired and wireless" },
  { brand: "HAVIT", model: "MS966", status: "pending", req: 0,
    note: "Wired USB" },
  { brand: "HXSJ", model: "J900", status: "pending", req: 5,
    note: "Wired USB" },
  { brand: "HXSJ", model: "A869", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "HyperX", model: "HXMS235", status: "pending", req: 1,
    note: "Wireless USB receiver" },
  { brand: "HyperX", model: "Pulsefire Haste 2 Mini Wireless", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "HyperX", model: "HXMS231", status: "pending", req: 0,
    note: "Wireless USB receiver" },
  { brand: "Incott", model: "HPC02 Pro", status: "pending", req: 0,
    note: "Wired and wireless" },
  { brand: "INPHIC", model: "IN9 Pro", status: "pending", req: 4,
    note: "Wired and wireless" },
  { brand: "INPHIC", model: "09 Tri-Mode Wireless", status: "pending", req: 1,
    note: "Bluetooth" },
  { brand: "INPHIC", model: "A9 Explorer V2", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "INPHIC", model: "F9", status: "pending", req: 0,
    note: "Not sure" },
  { brand: "INPHIC", model: "F9-MECHA", status: "pending", req: 0,
    note: "Wireless USB receiver" },
  { brand: "ipi", model: "Float 88", status: "pending", req: 3,
    note: "Wired and wireless" },
  { brand: "ipi", model: "QI Pro", status: "pending", req: 2,
    note: "Wired and wireless" },
  { brand: "ipi", model: "Fly", status: "pending", req: 0,
    note: "Wired and wireless" },
  { brand: "ISY", model: "IWM 1000", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "JLab", model: "GO", status: "pending", req: 1,
    note: "Not sure" },
  { brand: "KeepOut", model: "X9 Pro", status: "pending", req: 0,
    note: "Wired USB" },
  { brand: "Kensington", model: "Expert Wireless", status: "pending", req: 3,
    note: "Wireless USB receiver" },
  { brand: "Kensington", model: "Orbit Trackball With Scroll Ring", status: "pending", req: 2,
    note: "Wired USB" },
  { brand: "Keychron", model: "M7 8K", status: "pending", req: 2,
    note: "Wired and wireless" },
  { brand: "Kreo", model: "Hawk", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "Kreo", model: "Ikarus", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Kreo", model: "Chimera V1", status: "pending", req: 0,
    note: "Wireless USB receiver" },
  { brand: "Kreo", model: "Pegasus", status: "pending", req: 0,
    note: "Wired and wireless" },
  { brand: "Krux", model: "KRX0115", status: "pending", req: 0,
    note: "Wired USB" },
  { brand: "Kysona", model: "Mercury Pro", status: "pending", req: 6,
    note: "Wireless USB receiver" },
  { brand: "Kysona", model: "Aztec", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Kysona", model: "M600 V2", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Lamzu", model: "Maya", status: "pending", req: 4,
    note: "Wireless USB receiver" },
  { brand: "Lamzu", model: "Maya Champion Edition", status: "pending", req: 1,
    note: "Wireless USB receiver" },
  { brand: "Lamzu", model: "Thorn V2", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Lenovo", model: "IdeaPad Gaming M100", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "Lenovo", model: "Legion M410", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Lenovo", model: "Legion M600", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Lenovo", model: "Legion M600s", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Logitech", model: "MX Master 3", status: "pending", req: 12,
    note: "Wireless USB receiver" },
  { brand: "Logitech", model: "M510", status: "pending", req: 7,
    note: "Wireless USB receiver" },
  { brand: "Logitech", model: "Signature M650 / M650 L", status: "pending", req: 5,
    note: "Bluetooth" },
  { brand: "Logitech", model: "MR0083", status: "pending", req: 4,
    note: "Wired and wireless" },
  { brand: "Logitech", model: "Pebble M350s", status: "pending", req: 4,
    note: "Wireless USB receiver" },
  { brand: "Logitech", model: "G302 Daedalus Prime", status: "pending", req: 3,
    note: "Wired USB" },
  { brand: "Logitech", model: "M90", status: "pending", req: 3,
    note: "Wired USB" },
  { brand: "Logitech", model: "G602", status: "pending", req: 2,
    note: "Wireless USB receiver" },
  { brand: "Logitech", model: "Lift Vertical", status: "pending", req: 2,
    note: "Wireless USB receiver" },
  { brand: "Logitech", model: "Ergo M575S", status: "pending", req: 1,
    note: "Wireless USB receiver" },
  { brand: "Logitech", model: "G700", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Logitech", model: "G900", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Logitech", model: "M-R0057", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Logitech", model: "M170", status: "pending", req: 1,
    note: "Wireless USB receiver" },
  { brand: "Logitech", model: "M220", status: "pending", req: 1,
    note: "Wireless USB receiver" },
  { brand: "Logitech", model: "M330", status: "pending", req: 1,
    note: "Wireless USB receiver" },
  { brand: "Logitech", model: "M590", status: "pending", req: 1,
    note: "Wireless USB receiver" },
  { brand: "Logitech", model: "M705", status: "pending", req: 1,
    note: "Wireless USB receiver" },
  { brand: "Logitech", model: "M185", status: "pending", req: 0,
    note: "Wireless USB receiver" },
  { brand: "Logitech", model: "M190", status: "pending", req: 0,
    note: "Wireless USB receiver" },
  { brand: "Logitech", model: "M317", status: "pending", req: 0,
    note: "Wireless USB receiver" },
  { brand: "Logitech", model: "M550 L", status: "pending", req: 0,
    note: "Bluetooth" },
  { brand: "Logitech", model: "MX Master", status: "pending", req: 0,
    note: "Bluetooth" },
  { brand: "Mad Catz", model: "MMO TE", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "Mad Catz", model: "RAT 4+", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "Madlions", model: "MAD G+", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Mambasnake", model: "M3", status: "pending", req: 3,
    note: "Wireless USB receiver" },
  { brand: "Mambasnake", model: "M2", status: "pending", req: 0,
    note: "Wireless USB receiver" },
  { brand: "Marvo", model: "G912W", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Mchose", model: "A7X Ultra", status: "pending", req: 2,
    note: "Wired and wireless" },
  { brand: "Mchose", model: "G3 V2", status: "pending", req: 2,
    note: "Wired and wireless" },
  { brand: "Mchose", model: "G7", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Mistel", model: "Md750 Delight", status: "pending", req: 0,
    note: "Wired and wireless" },
  { brand: "Mloong", model: "MX301", status: "pending", req: 2,
    note: "Wired and wireless" },
  { brand: "Mloong", model: "MX302", status: "pending", req: 2,
    note: "Wireless USB receiver" },
  { brand: "Monka", model: "M1 Pro", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Monster Notebook", model: "Pusat One Shot Pro", status: "pending", req: 0,
    note: "Wired and wireless" },
  { brand: "MSI", model: "Clutch GM08", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "MSI", model: "Clutch GM41 Lightweight Wireless (Stalker 2 Edition)", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "MSI", model: "GM340", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "MSI", model: "Versa 300", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Noir Gear", model: "S1 Series", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "NOS", model: "M750", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "NOS", model: "M800", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Novotek", model: "MA-120", status: "pending", req: 0,
    note: "Wired USB" },
  { brand: "NYK", model: "Nemesis Neon MQ-32", status: "pending", req: 0,
    note: "Wired and wireless" },
  { brand: "NYK", model: "Nemesis Razor MQ-11", status: "pending", req: 0,
    note: "Wired and wireless" },
  { brand: "Onikuma", model: "CW917", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Onikuma", model: "CW921", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "Onikuma", model: "DM02", status: "pending", req: 1,
    note: "Not sure" },
  { brand: "Pichau", model: "Netuno Rainbow 01", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "Pictek", model: "T18", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "Pictek", model: "T7", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "Portronics", model: "Vader Max", status: "pending", req: 1,
    note: "Wireless USB receiver" },
  { brand: "Pulsar", model: "X2A V3", status: "pending", req: 4,
    note: "Wired and wireless" },
  { brand: "Pulsar", model: "X2 Mini", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Pulsar", model: "X2 V2", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Pulsar", model: "X2H V3 ES", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Pulsar", model: "X3 CrazyLight", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Pulsar", model: "X2N CrazyLight", status: "pending", req: 0,
    note: "Wired and wireless" },
  { brand: "Pwnage", model: "Symm 3", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Rakk", model: "Dasig", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Rakk", model: "Gahum", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Rapoo", model: "VT9 Pro", status: "pending", req: 4,
    note: "Wired and wireless" },
  { brand: "Rapoo", model: "M1620", status: "pending", req: 1,
    note: "Wireless USB receiver" },
  { brand: "Rapoo", model: "MT760 Pro", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Rapoo", model: "VT7 Air Max V2", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Rapoo", model: "V25", status: "pending", req: 0,
    note: "Wired USB" },
  { brand: "Rapoo", model: "V25S", status: "pending", req: 0,
    note: "Wired USB" },
  { brand: "Rapoo", model: "VT200", status: "pending", req: 0,
    note: "Wired and wireless" },
  { brand: "Rapoo", model: "VT3", status: "pending", req: 0,
    note: "Wireless USB receiver" },
  { brand: "Rapoo", model: "VT7 Max", status: "pending", req: 0,
    note: "Wired and wireless" },
  { brand: "Raptor", model: "Storm Grip Wireless", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Razer", model: "DeathAdder Essential (2021)", status: "pending", req: 4,
    note: "Wired USB" },
  { brand: "Razer", model: "RC30-030501", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Razer", model: "RZ01-0385", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "Redgear", model: "A10", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "Redgear", model: "X12 V2", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "Redgear", model: "A20", status: "pending", req: 0,
    note: "Wired USB" },
  { brand: "Redgear", model: "F-15", status: "pending", req: 0,
    note: "Wired USB" },
  { brand: "Redragon", model: "M607", status: "pending", req: 2,
    note: "Wired USB" },
  { brand: "Redragon", model: "Phaser M609", status: "pending", req: 2,
    note: "Wired USB" },
  { brand: "Redragon", model: "M712-RGB", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "Redragon", model: "M811-RGB", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "Redragon", model: "M908", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "Redragon", model: "M916 Pro 1K", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Redragon", model: "M919-ULT", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Redragon", model: "M994", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Redragon", model: "M998-ULT", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Redragon", model: "M808-KS", status: "pending", req: 0,
    note: "Wireless USB receiver" },
  { brand: "RedThunder", model: "M10", status: "pending", req: 1,
    note: "Bluetooth" },
  { brand: "Renew Force", model: "Viper Wireless BM-800", status: "pending", req: 1,
    note: "Wireless USB receiver" },
  { brand: "Rexus", model: "TP10", status: "pending", req: 13,
    note: "Wireless USB receiver" },
  { brand: "Rexus", model: "Daxa Air II Wired", status: "pending", req: 2,
    note: "Wired USB" },
  { brand: "Rexus", model: "DX-V1", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Rexus", model: "RX-115", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Rexus", model: "Clif II", status: "pending", req: 0,
    note: "Wireless USB receiver" },
  { brand: "Rexus", model: "Daxa Air Mini", status: "pending", req: 0,
    note: "Wired and wireless" },
  { brand: "Roccat", model: "Kone AIMO", status: "pending", req: 2,
    note: "Wired USB" },
  { brand: "Roccat", model: "XP", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "Rokytop", model: "TA1726492", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Royal Kludge", model: "M3", status: "pending", req: 3,
    note: "Wired and wireless" },
  { brand: "Sades", model: "Kojin MX10", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Sades", model: "Raiden Pro", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Scyrox", model: "V6", status: "pending", req: 9,
    note: "Wired and wireless" },
  { brand: "Shenzhen", model: "DZK01", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Skyshiu", model: "M3", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Smailwolf", model: "M3+", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Smailwolf", model: "M3 Pro+", status: "pending", req: 0,
    note: "Wireless USB receiver" },
  { brand: "Solakaka", model: "Sm600", status: "pending", req: 2,
    note: "Wireless USB receiver" },
  { brand: "Solakaka", model: "SM809 Pro", status: "pending", req: 2,
    note: "Wired and wireless" },
  { brand: "Solakaka", model: "E9 Pro", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Solakaka", model: "SM822", status: "pending", req: 0,
    note: "Wired and wireless" },
  { brand: "Sprime", model: "PM1", status: "pending", req: 0,
    note: "Wired and wireless" },
  { brand: "SteelSeries", model: "Aerox 3 Wireless", status: "pending", req: 8,
    note: "Wired and wireless" },
  { brand: "SteelSeries", model: "Rival 5", status: "pending", req: 4,
    note: "Wired USB" },
  { brand: "SteelSeries", model: "Aerox 3 Wireless Gen 2", status: "pending", req: 2,
    note: "Wired and wireless" },
  { brand: "SteelSeries", model: "Aerox 5 Wireless", status: "pending", req: 1,
    note: "Wireless USB receiver" },
  { brand: "SteelSeries", model: "M-00029", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "SteelSeries", model: "Rival 600", status: "pending", req: 0,
    note: "Wired USB" },
  { brand: "T-Dagger", model: "T-TGM205", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "T-Wolf", model: "G590", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "T-Wolf", model: "Q13", status: "pending", req: 1,
    note: "Wireless USB receiver" },
  { brand: "T-Wolf", model: "X9", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "T-Wolf", model: "X3", status: "pending", req: 0,
    note: "Wired and wireless" },
  { brand: "Tecknet", model: "TK-MS009", status: "pending", req: 1,
    note: "Wireless USB receiver" },
  { brand: "Tecknet", model: "UM013", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "Tecware", model: "EX2", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "The G-Lab", model: "Kult 170", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "TIETI", model: "M01R", status: "pending", req: 1,
    note: "Wireless USB receiver" },
  { brand: "TRONIC", model: "HG06607E", status: "pending", req: 1,
    note: "Wireless USB receiver" },
  { brand: "Trust", model: "GXT 109 Felox", status: "pending", req: 2,
    note: "Wired USB" },
  { brand: "Trust", model: "GXT 111 Neebo", status: "pending", req: 2,
    note: "Wired USB" },
  { brand: "Trust", model: "21090", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "Trust", model: "GST 170", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "Trust", model: "GXT 144 Rexx", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "Turbo-X", model: "Erebus EM10", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "Unctrl", model: "M1", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Urage", model: "Reaper 410", status: "pending", req: 2,
    note: "Wired USB" },
  { brand: "URX", model: "M1", status: "pending", req: 0,
    note: "Wireless USB receiver" },
  { brand: "UtechSmart", model: "Venus", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "UtechSmart", model: "Venus Pro Wireless", status: "pending", req: 0,
    note: "Wireless USB receiver" },
  { brand: "VGN", model: "F2 Pro Max", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "VGN", model: "Y2 Ultra", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "VGN", model: "F1 MOBA", status: "pending", req: 0,
    note: "Wired and wireless" },
  { brand: "VGUARD", model: "V6", status: "pending", req: 1,
    note: "Wired USB" },
  { brand: "VortexSeries", model: "Oni R1", status: "pending", req: 3,
    note: "Wired and wireless" },
  { brand: "VortexSeries", model: "Ignix F7", status: "pending", req: 2,
    note: "Not sure" },
  { brand: "VortexSeries", model: "Ignix F5 Pro", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "VortexSeries", model: "Inno X3 Pro", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Wraith", model: "W1", status: "pending", req: 2,
    note: "Wired and wireless" },
  { brand: "Xtrfy", model: "MZ1", status: "pending", req: 2,
    note: "Wireless USB receiver" },
  { brand: "Xtrfy", model: "M8", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Yeah Magic", model: "Tyrfig V1", status: "pending", req: 2,
    note: "Wireless USB receiver" },
  { brand: "Zaopin", model: "Z1 Pro", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Zaopin", model: "Z1 Pro Max", status: "pending", req: 1,
    note: "Wired and wireless" },
  { brand: "Zaopin", model: "Z2", status: "pending", req: 0,
    note: "Wireless USB receiver" },
  { brand: "Zebronics", model: "Transformer-M", status: "pending", req: 6,
    note: "Wired USB" },
  { brand: "Zowie", model: "ZA13-DW", status: "pending", req: 6,
    note: "Wired and wireless" },
  { brand: "Zowie", model: "EC1-CW", status: "pending", req: 2,
    note: "Wired and wireless" },
];

/**
 * Request votes for rows that `registrySupportedModels()` adds from the protocol
 * package. Frozen from the Supabase request catalog on 2026-09-24.
 */
export const REGISTRY_REQ: Record<string, number> = {
  "Fantech|WG14P Yari Pro Wireless 8K Gaming Mouse": 4,
  "G-Wolves|Fenrir Pro": 5,
  "G-Wolves|HTX": 1,
  "Glorious|Model I": 2,
  "Glorious|Model I 2 Wireless": 2,
  "Glorious|Model O 2 Wireless": 1,
  "Glorious|Model O Wireless": 7,
};
